import scrapy


class SearchSpider(scrapy.Spider):
    name = "search"
    allowed_domains = [
        'beaconpiping.com',
        'decco.com',
        'johnsonandjordan.com',
        'neair.com',
        'nbkenney.com',
        'denronph.com',
        'deltamechllc.com',
        'amerplumb.com',
        'h-m-inc.com',
        'neair.com',
        'shire.com',
        'mainhvac.com',
        'northernpeabody.com',
        'eamanti.com',
        'arcmech.com',
        'airetechmechanical.com',
        'notch.com',
        'northeasternmech.com',
        'leonelectric.com',
        'ranormech.com',
        'lakehvac.com',
        'allstateconstructioninc.com',
        'nsmech.com',
        'warrenmech.com',
        'mjmoraninc.com',
        'packtimco.com',
        'envsys.net',
        'maineenergy.net',
        'amivt.com',
        'cacmsi.com',
        'jec-company.com',
        'abmmechanical.com',
        'kleeberg.com',
        'marandola.net',
        'pittsfieldpipers.com',
        'ffmechanical.com',
        'pillsburysappliances.com',
        'rthmechanicalcontractors.com',
        'eckhardtjohnson.com',
        'fergusoncontractors.com',
        'pinnaclepiping.com',
        'bremco.com',
        'larkinhathaway.com',
        'performancecos.com',
        'americanstandardair.com',
        'enterpriseequip.com',
        'controlairsystems.com',
        'pecri.com',
        'uamservice.com',
        'jbmech.com',
        'modernmech.com',
        'hhs-mech.com',
        'camhvac.com',
        'linkmechanicalservices.net',
        'veteransdevelopmentcorp.com',
        'beaconmechanical.com',
        'bgpiping.com',
        'bradycompanies.com',
        'nasonmechanical.com',
        'hvacmcs.com',
        'blmechanical.com',
        'phmechanical.com',
        'damonmechanical.com',
        'cottijohnsonhvac.com',
        'buckinghamrouth.com',
        'sammechanical.com',
        'nutmegmechanical.com',
        'mccormick-allum.com',
        'northmechanical.net',
        'sauciermechanical.com',
        'haroldbros.com',
        'norrispreble.com',
        'commercialaircontrol.com',
        'fastco-corp.com',
        'mancinisheetmetal.com',
        'cmmoran.net',
        'brooksidemechanical.com',
        'cttempcontrols.com',
        'muirfieldmechanical.com',
        'oxfordats.com',
        'twtic.com',
        'gomechanical.com',
        'nectinc.com',
        'corpmech.com',
        'lincolnenergymechanical.com',
        'bbmsinc.com',
        'msimechanical.com',
        'mechdesignservices.com',
        'oatley.com',
        'jamestkay.com',
        'airtechnologiesinc.com',
        'theshaffercompany.com',
        'donovans.org',
        'interstatems.com',
        'megamechanical.com',
        'eomech.com',
        'sarraengineering.com',
        'harpmech.com',
        'ne-fab.com',
        'advancedmechanical.net',
        'excelmechanical.com',
        'mercurymechanical.com',
        'deltamechanical.com',
        'riversidemechanicalinc.com',
        'phoenixmechanical.com',
        'olivermechanicalinc.com',
        'stevenselectricandpump.com',
        'ssservicecorp.com',
        '2020air.net',
        'usamech.com',
        'zonemech.com',
        'wnharris.com',
        'avondaair.com',
        'sigmams.com',
        'processpipingcompany.com',
        'nepsi.net',
        'sarraengineering.com',
        'masco-hvac.com',
        'paradigmph.com',
        'rockfallco.com',
        'emonds.com',
        'combustioninstallations.com',
        'milharmer.com',
        'lrhvac.com',
        'accuratemechanicalcorp.com',
        'centralmechct.com',
        'cstonemechanical.com',
        'advancedmechanicalct.com',
        'ldgcorporation.com',
        'ashleyswift.com',
        'wcmechanical.net',
        'rmncontrolsolutions.com',
        'maineboiler.com',
        'energy-one.com',
        'mechairne.com',
        'cwclancy.com',
        'tjconway.com',
        'dfplumbingandmechanical.com',
        'atlanticmechman.com',
        'mpcservicesinc.com',
        'jcoyne.com',
        'gelinashvac.com',
        'xlmechanical.com',
        'mechanicalconcepts-inc.com',
        'patriotambulance.com',
        'imec-us.com',
        'alphamechanicalcorp.com',
        'westmechanical.com',
        'pdmechanical-inc.com',
        'burnsmechanicalcorp.net',
        'elitemechanicalcontractors.com',
        'chasemechanical.com',
        'rockportmechanical.com',
        'bostonmechanicalservices.com',
        'briggsmechanical.com',
        'specialtyservicesme.com',
        'spathson.com',
        'commercialboilersystems.com',
        'accuaireinc.com',
        'morrismech.com',
        'richmancapital.com',
        'absolutemechanical.com',
        'generalinc.com',
        'macriassociates.com',
        'trustthisbiz.com',
        'brideandgrimes.com',
        'mecannica.com'        
    ]

    start_urls = [        
        'http://beaconpiping.com/',
        'http://decco.com/',
        'http://johnsonandjordan.com/',
        'http://neair.com/',
        'http://nbkenney.com/',
        'http://denronph.com/',
        'http://deltamechllc.com/',
        'http://amerplumb.com/',
        'http://h-m-inc.com/',
        'http://neair.com/',
        'http://shire.com/',
        'http://mainhvac.com/',
        'http://northernpeabody.com/',
        'http://eamanti.com/',
        'http://arcmech.com/',
        'http://airetechmechanical.com/',
        'http://notch.com/',
        'http://northeasternmech.com/',
        'http://leonelectric.com/',
        'http://ranormech.com/',
        'http://lakehvac.com/',
        'http://allstateconstructioninc.com/',
        'http://nsmech.com/',
        'http://warrenmech.com/',
        'http://mjmoraninc.com/',
        'http://packtimco.com/',
        'http://envsys.net/',
        'http://maineenergy.net/',
        'http://amivt.com/',
        'http://cacmsi.com/',
        'http://jec-company.com/',
        'http://abmmechanical.com/',
        'http://kleeberg.com/',
        'http://marandola.net/',
        'http://pittsfieldpipers.com/',
        'http://ffmechanical.com/',
        'http://pillsburysappliances.com/',
        'http://rthmechanicalcontractors.com/',
        'http://eckhardtjohnson.com/',
        'http://fergusoncontractors.com/',
        'http://pinnaclepiping.com/',
        'http://bremco.com/',
        'http://larkinhathaway.com/',
        'http://performancecos.com/',
        'http://americanstandardair.com/',
        'http://enterpriseequip.com/',
        'http://controlairsystems.com/',
        'http://pecri.com/',
        'http://uamservice.com/',
        'http://jbmech.com/',
        'http://modernmech.com/',
        'http://hhs-mech.com/',
        'http://camhvac.com/',
        'http://linkmechanicalservices.net/',
        'http://veteransdevelopmentcorp.com/',
        'http://beaconmechanical.com/',
        'http://bgpiping.com/',
        'http://bradycompanies.com/',
        'http://nasonmechanical.com/',
        'http://hvacmcs.com/',
        'http://blmechanical.com/',
        'http://phmechanical.com/',
        'http://damonmechanical.com/',
        'http://cottijohnsonhvac.com/',
        'http://buckinghamrouth.com/',
        'http://sammechanical.com/',
        'http://nutmegmechanical.com/',
        'http://mccormick-allum.com/',
        'http://northmechanical.net/',
        'http://sauciermechanical.com/',
        'http://haroldbros.com/',
        'http://norrispreble.com/',
        'http://commercialaircontrol.com/',
        'http://fastco-corp.com/',
        'http://mancinisheetmetal.com/',
        'http://cmmoran.net/',
        'http://brooksidemechanical.com/',
        'http://cttempcontrols.com/',
        'http://muirfieldmechanical.com/',
        'http://oxfordats.com/',
        'http://twtic.com/',
        'http://gomechanical.com/',
        'http://nectinc.com/',
        'http://corpmech.com/',
        'http://lincolnenergymechanical.com/',
        'http://bbmsinc.com',
        'http://msimechanical.com/',
        'http://mechdesignservices.com/',
        'http://oatley.com/',
        'http://jamestkay.com/',
        'http://airtechnologiesinc.com/',
        'http://theshaffercompany.com/',
        'http://donovans.org/',
        'http://interstatems.com/',
        'http://megamechanical.com/',
        'http://eomech.com/',
        'http://sarraengineering.com/',
        'http://harpmech.com/',
        'http://ne-fab.com/',
        'http://advancedmechanical.net/',
        'http://excelmechanical.com/',
        'http://mercurymechanical.com/',
        'http://deltamechanical.com/',
        'http://riversidemechanicalinc.com/',
        'http://phoenixmechanical.com/',
        'http://olivermechanicalinc.com/',
        'http://stevenselectricandpump.com/',
        'http://ssservicecorp.com/',
        'http://2020air.net/',
        'http://usamech.com/',
        'http://zonemech.com/',
        'http://wnharris.com/',
        'http://avondaair.com/',
        'http://sigmams.com/',
        'http://processpipingcompany.com/',
        'http://nepsi.net/',
        'http://sarraengineering.com/',
        'http://masco-hvac.com/',
        'http://paradigmph.com/',
        'http://rockfallco.com/',
        'http://emonds.com/',
        'http://combustioninstallations.com/',
        'http://milharmer.com/',
        'http://lrhvac.com/',
        'http://accuratemechanicalcorp.com/',
        'http://centralmechct.com/',
        'http://cstonemechanical.com/',
        'http://advancedmechanicalct.com/',
        'http://ldgcorporation.com/',
        'http://ashleyswift.com/',
        'http://wcmechanical.net/',
        'http://rmncontrolsolutions.com/',
        'http://maineboiler.com/',
        'http://energy-one.com/',
        'http://mechairne.com/',
        'http://cwclancy.com/',
        'http://tjconway.com/',
        'http://dfplumbingandmechanical.com/',
        'http://atlanticmechman.com/',
        'http://mpcservicesinc.com/',
        'http://jcoyne.com/',
        'http://gelinashvac.com/',
        'http://xlmechanical.com/',
        'http://mechanicalconcepts-inc.com/',
        'http://patriotambulance.com/',
        'http://imec-us.com/',
        'http://alphamechanicalcorp.com/',
        'http://westmechanical.com/',
        'http://pdmechanical-inc.com/',
        'http://burnsmechanicalcorp.net/',
        'http://elitemechanicalcontractors.com/',
        'http://chasemechanical.com/',
        'http://rockportmechanical.com/',
        'http://bostonmechanicalservices.com/',
        'http://briggsmechanical.com/',
        'http://specialtyservicesme.com/',
        'http://spathson.com/',
        'http://commercialboilersystems.com/',
        'http://accuaireinc.com/',
        'http://morrismech.com/',
        'http://richmancapital.com/',
        'http://absolutemechanical.com/',
        'http://generalinc.com/',
        'http://macriassociates.com/',
        'http://trustthisbiz.com/',
        'http://brideandgrimes.com/',
        'http://mecannica.com/'
    ]

    keywords = [
        'BIM Modeling',
        'CAD',
        'mechanical',
        'industrial',
        'piping',
        'power generation'
    ]
    initvalue = {
        'url':'URL',
        'BIM Modeling':0,
        'CAD':0,
        'mechanical':0,
        'industrial':0,
        'piping':0,
        'power generation':0    
    }
    limitwords = [
        'pdf',
        'jpg',
        'png',
        'mailto:',
        'javascript',
        'tel:',
        'mp4',
        'JPG'
    ]
    # def start_requests(self):
    #     for url in self.urls:
    #         yield scrapy.Request(url=url, callback=self.parse)

    def parse(self, response):
    
        result = self.initvalue
        body = response.body
        baseurl = response.url.split("/")[2]
        if 'www.' == baseurl[0:4]:
            baseurl = baseurl[4:]
        # result['url'] = response.url
        result['url'] = baseurl

        for keyword in self.keywords:
            if keyword in body:
                result[keyword] = 1
            else:
                result[keyword] = 0;

        for href in response.css('a::attr(href)'):
            testhref = href.extract()
            
            # if 'http' in testhref:  
            #     if not baseurl in testhref.split("?")[0]:
            #         continue
            limitflag = False
            for limitword in self.limitwords:
                if limitword in testhref:
                    limitflag = True
                    break
            if limitflag:
                continue

            yield response.follow(href, self.parse)

        yield result
